project.version=5.2.1+26.1.2
project.java=25
project.build-java=25
project.minecraft=26.1.2
project.enabled-loaders=fabric,forge,neoforge
project.catalog-name=libsMc2612
project.catalog-coordinate=com.iamkaf.platform:mc-26.1.2:26.1.2-SNAPSHOT

mixin.compat.common=JAVA_21
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_21
mixin.compat.neoforge=JAVA_21

mod.minecraft-range=[26.1.2, 27)
mod.fabric-range=>=26.1.2
mod.forge-loader-range=[62,)
mod.neoforge-loader-range=[4,)

publish.game-versions=26.1.2
