project.version=5.3.0+26.3
project.java=25
project.build-java=25
project.minecraft=26.3
project.enabled-loaders=fabric

mixin.compat.common=JAVA_21
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_21
mixin.compat.neoforge=JAVA_21

mod.minecraft-range=>=26.3-pre.2
mod.fabric-range=>=26.3-pre.2
mod.forge-loader-range=[65,)
mod.neoforge-loader-range=[4,)

publish.game-versions=26.3-pre-2
