name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: iamkaf/multiloader-conventions/.github/workflows/mod-build.yml@49456a45df2cb44dac296709dc74553a2173900f
