name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: iamkaf/multiloader-conventions/.github/workflows/mod-build.yml@e808aac57fd30afcfc3e7b517f88b3143fd3211d
