name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: iamkaf/multiloader-conventions/.github/workflows/mod-build.yml@c0ae7d9d2950cf1bf7894bbda00e0e7636eebe9e
    with:
      teakit-runner: gradle
